name: BASwiftKitDemo
options:
  bundleIdPrefix: com.baswiftkit
  deploymentTarget:
    iOS: 15.0
  developmentLanguage: zh-Hans
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 5.7
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  BASwiftKitDemo:
    type: application
    platform: iOS
    sources:
      - path: BASwiftKitDemo
        excludes:
          - "Resources/Info.plist"
    info:
      path: BASwiftKitDemo/Resources/Info.plist
      properties:
        CFBundleDisplayName: BASwiftKit
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        NSCameraUsageDescription: 用于演示 BASwiftKit 扫一扫功能。
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIUserInterfaceStyle: Automatic
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).BASceneDelegate
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.baswiftkit.demo
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
